### ISSUE TITLE
Error Push

### ISSUE THREAD

**Issue by Montaner32** [maestria-geotel-201902/unidad-1-asignacion-2-rasters-y-exportar-datos-espaciales-Montaner32#1]
>>> git push origin refs/heads/master
To https://github.com/maestria-geotel-201902/unidad-0-asignacion-99-mi-proyecto-Montaner32.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/maestria-geotel-201902/unidad-0-asignacion-99-mi-proyecto-Montaner32.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
@geofis

**Comment by geofis** [comment]
@Montaner32. El *issue* al parecer es sobre el repo "unidad-0-asignacion-99-mi-proyecto-Montaner32", pero creaste el *issue* en el repo "unidad-1-asignacion-2-rasters-y-exportar-datos-espaciales-Montaner32". Asumo que el problema en cuestión se refiere al primer repo, pero la próxima vez, coloca el *issue* donde corresponda.

Es probable que hayas hecho *commit* con *amend*. ¿Haz hecho algún *commit*? Si no hay cambios hechos, es fácil, pero antes habría que saber si tienes algún *commit* hecho.

**Comment by geofis** [comment]
@Montaner32 Revisé también el repo "unidad-1-asignacion-2-rasters-y-exportar-datos-espaciales-Montaner32", y veo que tienes dos *commit* hechos con la opción "*Amend previous commit*". Dicha opción debía estar desactivada, pero ahora tienes el problema de que tu *commit* se fundió con el original. Intentaré resolverlo por vía de comandos. Cuando lo corrija (si lo logro) harás *commit* nuevamente (te avisaré), pero no marques la opción "*Amend previous commit*".

**Comment by geofis** [comment]
@Montaner32 Hice *commit*>*push* con mi usuario para verificar que se pudo hacer el *reset*. Toma nota: **NO** marcar la opción "*Amend previous commit*" en futuras asignaciones.
